# variables
substitutions:
  name: 'Arlec PC190HA 01'
  device: 'arlec_PC190HA_01'
  
esphome:
  name: ${device}
  comment: ${name}
  platform: ESP8266
  board: esp01_1m

wifi:
#  ssid: "rYELLOW"   #your wifi goes here
#  password: "password" #your wifi pw goes here
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Arlec PC190HA 01 Fallback Hotspot"
    password: #"password"


captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: uptime
    name: ${name} Uptime

  - platform: wifi_signal
    name: ${name} Signal
    update_interval: 300s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      inverted: True
    name: ${name} button
    on_multi_click:
      # Support a single or double click to switch on each relay
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - switch.toggle: relay_a


switch:
  - platform: gpio
    pin: GPIO12
    name: "${name} - A"
    id: relay_a
    restore_mode: always off
    icon: mdi:power-socket-au
    on_turn_on:
      - light.dim_relative:
          id: led
          relative_brightness: 50%
    on_turn_off:
      - light.dim_relative:
          id: led
          relative_brightness: -50%


# Use PWM controlled LED to indicate state
light:
  - platform: monochromatic
    name: "${name} - LED"
    id: led
    internal: True
    output: gpio13
    restore_mode: always off

output:
  - platform: esp8266_pwm
    id: gpio13
    pin:
      number: GPIO13
      inverted: True
